### PR TITLE
Date format support 

### PR DESCRIPTION
**Pull request by blackfalcon**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #72

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

Commits to blocks of work;

1. Update packages, dev dependency on `marked` is not needed
2. Refactor code to move all functions to `base-input.js` made no sense as to what was in base versus what was in the component js file
3. Add date format support

See demo: https://input-dateformat-issue72.surge.sh/

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by leeejune — COMMENTED** [review]
The intended behavior is that the date formatting appears by default without having the user click into it (refer to blueprint "Default" state). Is this a possible behavior to have?

**Comment by leeejune** [comment]
@blackfalcon 
1. Text for borderless version should not be white (should be transparent)
2. Background in bordered input should be white

**Comment by blackfalcon** [comment]
For reference... 

> The intended behavior is that the date formatting appears by default without having the user click into it (refer to blueprint "Default" state). Is this a possible behavior to have?

It was discussed that this is a break from how all the other input elements work and there is not clear enough data to support moving in this direction at this time.

**Comment by blackfalcon** [comment]
> 



> @blackfalcon
> 
> 1. Text for borderless version should not be white (should be transparent)
> 2. Background in bordered input should be white

@leeejune [input-dateformat-issue72.surge.sh](https://input-dateformat-issue72.surge.sh/) has been updated

**Comment by leeejune** [comment]
@blackfalcon Is this intended? If not, the white text should be translucent (since the background is translucent).

Screen Shot 2021-12-01 at 2 57 15 AM

**Comment by blackfalcon** [comment]
Updated code and Surge demo 

Screen Shot 2021-11-30 at 2 50 27 PM

**Review by leeejune — APPROVED** [review]

**Review by jason-capsule42 — APPROVED** [review]

**Pull request merged**
