### PR TITLE
Repo upgrade

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #15, #50 

## Summary:

This change updates the repo to generator v3.7.1.

Note that this repo is not fully in compliance with the style lint rules included in the 3.7.1 version of the generator. Ticket #50 was opened to address that significant work separately.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
The commit message needs the `BREAKING CHANGE` addition in order to kick off a MAJOR version release using the new `@aurodesignsystem` npm namespace. 

The Repository secrets need to be updated as well in order to talk to the new npm namespace account.

**Review by blackfalcon — CHANGES_REQUESTED** [review]

**Review by blackfalcon — APPROVED** [review]

**Comment by blackfalcon** [comment]
This PR is approved, but we first need to add a deprecation warning to the legacy version of this repo to alert users that the updated version will be at a new npm namespace.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
I just ran the rebase on `next` and `repoUpgrade` and I noticed that the tests are broken? 

Please review https://github.com/AlaskaAirlines/auro-input/runs/3137875164?check_suite_focus=true#step:5:114

**Comment by jason-capsule42** [comment]
> I just ran the rebase on `next` and `repoUpgrade` and I noticed that the tests are broken?
> 
> Please review https://github.com/AlaskaAirlines/auro-input/runs/3137875164?check_suite_focus=true#step:5:114

@blackfalcon please reassess here. I just rebased off next and all tests are passing for me. This PR should still be ready to merge.

**Comment by blackfalcon** [comment]
@jason-capsule42 please review ASAP. 

I pulled down a clean version of the repo, installed packaged and ran `npm run build` and I still see the following CLI log

```shell
test/auro-input.test.js:

 🚧 Browser logs:
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Cc Amex</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Cc Amex</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Cc Amex</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:222:5)'
      }
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Cc Amex</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Cc Amex</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Cc Amex</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:231:5)'
      }
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Cc Visa</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Cc Visa</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Cc Visa</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:240:5)'
      }
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Cc Mastercard</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Cc Mastercard</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Cc Mastercard</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:249:5)'
      }
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Cc Discover</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Cc Discover</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Cc Discover</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:258:5)'
      }
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Credit Card</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Credit Card</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Credit Card</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:267:5)'
      }
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Credit Card</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Credit Card</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Credit Card</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:276:5)'
      }
      An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
      {
        name: 'AssertionError',
        message: "expected '' to contain HTML '<title>Cc Alaska</title>'",
        showDiff: true,
        actual: '',
        expected: '<title>Cc Alaska</title>',
        operator: 'strictEqual',
        stack: "AssertionError: expected '' to contain HTML '<title>Cc Alaska</title>'\n" +
          '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
          '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:285:5)'
      }

Chrome: |██████████████████████████████| 1/1 test files | 26 passed, 0 failed

Code coverage: 98.21 %
View full coverage report at coverage/lcov-report/index.html

Finished running tests in 2s, all tests passed! 🎉
```

The tests do pass, but this needs to be corrected prior to merging.

**Comment by jason-capsule42** [comment]
> @jason-capsule42 please review ASAP.
> 
> I pulled down a clean version of the repo, installed packaged and ran `npm run build` and I still see the following CLI log
> 
> ```shell
> test/auro-input.test.js:
> 
>  🚧 Browser logs:
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Cc Amex</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Cc Amex</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Cc Amex</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:222:5)'
>       }
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Cc Amex</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Cc Amex</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Cc Amex</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:231:5)'
>       }
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Cc Visa</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Cc Visa</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Cc Visa</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:240:5)'
>       }
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Cc Mastercard</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Cc Mastercard</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Cc Mastercard</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:249:5)'
>       }
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Cc Discover</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Cc Discover</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Cc Discover</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:258:5)'
>       }
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Credit Card</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Credit Card</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Credit Card</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:267:5)'
>       }
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Credit Card</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Credit Card</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Credit Card</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:276:5)'
>       }
>       An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
>       {
>         name: 'AssertionError',
>         message: "expected '' to contain HTML '<title>Cc Alaska</title>'",
>         showDiff: true,
>         actual: '',
>         expected: '<title>Cc Alaska</title>',
>         operator: 'strictEqual',
>         stack: "AssertionError: expected '' to contain HTML '<title>Cc Alaska</title>'\n" +
>           '    at validateCardIcon (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:291:37)\n' +
>           '    at o.<anonymous> (http://localhost:8000/test/auro-input.test.js?wtr-session-id=7f8a9271-37ec-4114-b69d-0c9b58c7021b:285:5)'
>       }
> 
> Chrome: |██████████████████████████████| 1/1 test files | 26 passed, 0 failed
> 
> Code coverage: 98.21 %
> View full coverage report at coverage/lcov-report/index.html
> 
> Finished running tests in 2s, all tests passed! 🎉
> ```
> 
> The tests do pass, but this needs to be corrected prior to merging.

@blackfalcon These tests have been fixed.

**Review by blackfalcon — APPROVED** [review]

**Pull request merged**
